### ISSUE TITLE
Vsp st. 1: "Of hearing" is hard to understand

### ISSUE THREAD

**Issue by jgnewman** [martensas/edda#35]
> Of hearing I bid all holy kinds, the greater and lesser sons of Homedall

I don't understand what is meant by "of hearing". It looks as though _hljóðs_ is genitive, and I'm having a hard time converting that literally into English as well. Is she asking for an audience to listen to her? If so, I wonder if a more understandable phrasing might be something like: "Hearing, I bid, from all holy kinds"

**Comment by martensas** [comment]
She's asking for them to shut up and listen essentially. I changed "Of hearing I bid all holy kinds" to "For hearing I ask all holy races".
