### ISSUE TITLE
Vsp. St. 4: "they who the renowned Middenyard shaped"

### ISSUE THREAD

**Issue by jgnewman** [martensas/edda#39]
> Before the sons of Bur the flatlands did upwards lift, they who the renowned Middenyard shaped.

It took me a minute to understand that this wasn't saying Middenyard shaped the sons of Bur. Even though your word order matches the O.N. here and even though we can sometimes be a little flexible with word order in English poetry, I highly recommend in this case going with "they who shaped the renowned Middenyard".

**Comment by martensas** [comment]
This has been resolved a while ago.
