### ISSUE TITLE
Vsp: St. 5: "where halls she owned"

### ISSUE THREAD

**Issue by jgnewman** [martensas/edda#41]
> Sun knew not, where halls she owned; stars knew not, where steads they owned; Moon knew not, what of might he owned.

Some of the word order in here feels a bit awkward to me. I recommend...

> Sun knew not, where she owned **halls**; stars knew not, where they owned **steads**; Moon knew not, **of what** might he owned.

**Comment by martensas** [comment]
I use this word order for the emphasis on these words, I hope it's still understandable. "what of might" is an interesting construction, compare "What is that of men?"—it essentially means "what sort of might". I will change it to that.

**Comment by jgnewman** [comment]
I think that works. The word order in the earlier parts feels more normally to me on a second look. But I would have still pushed for a change to the last piece.
