### ISSUE TITLE
Vsp. St. 8: "was for them no lack of gold

### ISSUE THREAD

**Issue by jgnewman** [martensas/edda#42]
> They played Tavel in the yards, joyous were they: was for them no lack of gold

Not sure of the technical, grammatical way to say this but, "was" is like an equals sign and it's missing the left side of the equation here. We need something like "there was for them no lack of gold" or "no lack of gold was for them", or something along those lines.

Btw, I _love_ "Ettinham".

**Comment by martensas** [comment]
Solved in upcoming version.
