### ISSUE TITLE
Vsp. St. 15 - Suggest adding "Dreepen" to the index

### ISSUE THREAD

**Issue by jgnewman** [martensas/edda#45]
At this point I'm starting to get a feel for the direction you've chosen for English-ifying words so I won't suggest calling this "Dripper", but I do think it would be good to call out that the name is etymologically related to "drip" and that ~~using this word as slang for impressive attire is not an invention of Gen Z~~ as per Snorri (Skld. 32, 35) it "drips" out more gold.

**Comment by martensas** [comment]
All proper nouns will be added to the Index
