### ISSUE TITLE
Vsp. St. 62: "Roft <= Weden>"

### ISSUE THREAD

**Issue by jgnewman** [martensas/edda#59]
I'm noticing that sometimes you use footnotes for this type of thing (see "bane of Bellow" in st. 53, for example) and sometimes you use "thing <= other thing>". I recommend settling on a rule for when you will use each one or, perhaps better yet, I think I would prefer footnotes in all cases. The reason being, I already know what most of these references are and prefer not to have extra text cluttering up the translation.

**Comment by martensas** [comment]
I've chosen to follow the SkP standard and thus use <> and [] in all these cases, instead using the footnotes for deeper explanation. I agree that it can become unbearable at times, though.
